version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ctvalga_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Automatiza la creación de tablas al arrancar por primera vez
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend-api
    container_name: ctvalga_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./scripts:/app/scripts
    depends_on:
      - db

  frontend-server:
    build: ./node-server
    container_name: ctvalga_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./node-server:/app
    depends_on:
      - backend

volumes:
  postgres_data: